name: thebox
title: thebox
url: "https://theboxahaan.github.io" 
highlighter: rouge 
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'